### ISSUE TITLE
ModuleNotFoundError: No module named 'package.cry'

### ISSUE THREAD

**Issue by ch3e3rs** [chenak-a/CryptoStoreAI#1]
After update all dependencies, I got this exception:
ModuleNotFoundError: No module named 'package.cry'

After `adding cry==0.2.3` into requirements.txt and changing `import package.cry as cry` to `import cry` I got this exception:
`File "/app/package/crypto.py", line 196, in initialization
    rsi = cry.EWMArsi(df["Close"], 14)
AttributeError: module 'cry' has no attribute 'EWMArsi'
`
Thx for your help.

**Comment by chenak-a** [comment]
Hi
this repo is only for demonstration purposes and yes I know there are 2 things that I did t put in this repo cry package and Ai models. if you wanna use my bot and my Ai models you have to wait for my website to go out. I am working on it write now.
Thank you for your interest

**Comment by ch3e3rs** [comment]
Hi, thanks for your response.
